### PR TITLE
Switch to TemporaryComtrpoller

### PR DESCRIPTION
**Pull request by hayesgm**

### CODE REVIEW

**Review by jflatow — APPROVED** [review]

**Review by DioXi95 — COMMENTED** [review]
{
    "Contracts": {
        "ZRX": "0xddea378A6dDC8AfeC82C36E9b0078826bf9e68B6",
        "cUSDC": "0x5B281A6DdA0B271e91ae35DE655Ad301C976edb1",
        "PriceOracle": "0xD2B1eCa822550d9358e97e72c6C1a93AE28408d0",
        "ZeroComptroller": "0x16e175eE9f555E43FD01f3aFa359A37b10e5139b",
        "PriceOracleProxy": "0x5722A3F60fa4F0EC5120DCD6C386289A4758D1b2",
        "Maximillion": "0xFBBDBa59516adA2eADf50f96cE0151edC9e0A674",
        "Base200bps_Slope2000bps_Jump20000bps_Kink90": "0x5e237767da01d6fEF0D238aFe6a1EE02c43D8218",
        "cDAI": "0x6D7F0754FFeb405d23C51CE938289d4835bE3b14",
        "CompoundLens": "0x2B833E2D24ac3c246664b986554A7485fDf75D8b",
        "DAI": "0x5592EC0cfb4dbc12D3aB100b257153436a1f0FEa",
        "StdComptroller": "0x99127FD9840Cbc2bBfF43dF443887f4d96268916",
        "Unitroller": "0x2EAa9D77AE4D8f9cdD9FAAcd44016E746485bddb",
        "USDT": "0xD9BA894E0097f8cC2BBc9D24D308b98e36dc6D02",
        "Comptroller": "0x2EAa9D77AE4D8f9cdD9FAAcd44016E746485bddb",
        "cUSDT": "0x2fB298BDbeF468638AD6653FF8376575ea41e768",
        "cBAT": "0xEBf1A11532b93a529b5bC942B4bAA98647913002",
        "Base0bps_Slope2000bps": "0x1A43BFd39B15DcF444e17Ab408C4b5be32DEB7F5",
        "BAT": "0xbF7A7169562078c96f0eC1A8aFD6aE50f12e5A99",
        "cETH": "0xd6801a1DfFCd0a410336Ef88DeF4320D6DF1883e",
        "cUsdtDelegate": "0x98394a121D26F90F4841e7BFE9dD4Aba05E666E4",
        "Base500bps_Slope1200bps": "0xE12630c8Fdd7d0096c9Cd72Cd228598AEBe58795",
        "Timelock": "0xe4cD9a61431FbD268ea842D68533561262C17513",
        "Base200bps_Slope3000bps": "0x6330D442A2D7eE4DC66C0adb9969e8702aEfc9fE",
        "cREP": "0xEBe09eB3411D18F4FF8D859e096C533CAC5c6B60",
        "ComptrollerG2": "0xb1983eE0064Fdb2A581966715DC9bA4D8B289A6A",
        "WBTC": "0x577D296678535e4903D59A4C929B718e1D575e0A",
        "REP": "0x6e894660985207feb7cf89Faf048998c71E8EE89",
        "cZRX": "0x52201ff1720134bBbBB2f6BC97Bf3715490EC19B",
        "cWBTC": "0x0014F450B8Ae7708593F4A46F8fa6E5D50620F96",
        "USDC": "0x4DBCdF9B62e891a7cec5A2568C3F4FAF9E8Abe2b"
    },
    "Blocks": {
        "cUSDC": 4319847,
        "ZeroComptroller": 4347719,
        "PriceOracleProxy": 6402199,
        "Maximillion": 4319848,
        "Base200bps_Slope2000bps_Jump20000bps_Kink90": 6402170,
        "cDAI": 4319844,
        "CompoundLens": 6312618,
        "StdComptroller": 4319836,
        "Unitroller": 4319835,
        "USDT": 6402171,
        "cUSDT": 6402173,
        "cBAT": 4319843,
        "Base0bps_Slope2000bps": 4319840,
        "cETH": 4319846,
        "cUsdtDelegate": 6402172,
        "Base500bps_Slope1200bps": 4319839,
        "Timelock": 5245966,
        "Base200bps_Slope3000bps": 4319841,
        "cREP": 4319845,
        "ComptrollerG2": 5245967,
        "WBTC": 4717533,
        "cZRX": 4319842,
        "cWBTC": 4717535
    },
    "PriceOracleProxy": {
        "description": "Price Oracle Proxy",
        "cETH": "0xd6801a1DfFCd0a410336Ef88DeF4320D6DF1883e",
        "cUSDC": "0x5B281A6DdA0B271e91ae35DE655Ad301C976edb1",
        "cSAI": "0x6D7F0754FFeb405d23C51CE938289d4835bE3b14",
        "cDAI": "0x6D7F0754FFeb405d23C51CE938289d4835bE3b14",
        "cUSDT": "0x2fB298BDbeF468638AD6653FF8376575ea41e768",
        "address": "0x5722A3F60fa4F0EC5120DCD6C386289A4758D1b2"
    },
    "Maximillion": {
        "description": "Maximillion",
        "cEtherAddress": "0xd6801a1DfFCd0a410336Ef88DeF4320D6DF1883e",
        "address": "0xFBBDBa59516adA2eADf50f96cE0151edC9e0A674"
    },
    "CompoundLens": {
        "name": "CompoundLens",
        "contract": "CompoundLens"
    },
    "Unitroller": {
        "description": "Unitroller",
        "address": "0x2EAa9D77AE4D8f9cdD9FAAcd44016E746485bddb"
    },
    "Comptroller": {
        "StdComptroller": {
            "address": "0x99127FD9840Cbc2bBfF43dF443887f4d96268916",
            "contract": "Comptroller",
            "description": "Standard Comptroller Impl"
        },
        "ZeroComptroller": {
            "address": "0x16e175eE9f555E43FD01f3aFa359A37b10e5139b",
            "contract": "Comptroller",
            "description": "Standard Comptroller Impl"
        },
        "ComptrollerG2": {
            "address": "0xb1983eE0064Fdb2A581966715DC9bA4D8B289A6A",
            "contract": "Comptroller",
            "description": "Standard Comptroller Impl"
        }
    },
    "Timelock": {
        "address": "0xe4cD9a61431FbD268ea842D68533561262C17513",
        "contract": "Timelock",
        "description": "Test Timelock"
    },
    "Constructors": {
        "ZRX": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000002307800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000035a52580000000000000000000000000000000000000000000000000000000000",
        "cUSDC": "0x0000000000000000000000004dbcdf9b62e891a7cec5a2568c3f4faf9e8abe2b0000000000000000000000002eaa9d77ae4d8f9cdd9faacd44016e746485bddb0000000000000000000000001a43bfd39b15dcf444e17ab408c4b5be32deb7f50000000000000000000000000000000000000000000000000000b5e620f4800000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000016436f6d706f756e642055534420436f696e20f09f93880000000000000000000000000000000000000000000000000000000000000000000000000000000000056355534443000000000000000000000000000000000000000000000000000000",
        "ZeroComptroller": "0x",
        "PriceOracleProxy": "0x0000000000000000000000009c1856636d78c051dead6cab9c5699e4e25549e9000000000000000000000000d2b1eca822550d9358e97e72c6c1a93ae28408d0000000000000000000000000d6801a1dffcd0a410336ef88def4320d6df1883e0000000000000000000000005b281a6dda0b271e91ae35de655ad301c976edb10000000000000000000000006d7f0754ffeb405d23c51ce938289d4835be3b140000000000000000000000006d7f0754ffeb405d23c51ce938289d4835be3b140000000000000000000000002fb298bdbef468638ad6653ff8376575ea41e768",
        "Maximillion": "0x000000000000000000000000d6801a1dffcd0a410336ef88def4320d6df1883e",
        "Base200bps_Slope2000bps_Jump20000bps_Kink90": "0x00000000000000000000000000000000000000000000000000470de4df82000000000000000000000000000000000000000000000000000002c68af0bb1400000000000000000000000000000000000000000000000000001bc16d674ec800000000000000000000000000000000000000000000000000000c7d713b49da0000",
        "cDAI": "0x0000000000000000000000005592ec0cfb4dbc12d3ab100b257153436a1f0fea0000000000000000000000002eaa9d77ae4d8f9cdd9faacd44016e746485bddb000000000000000000000000e12630c8fdd7d0096c9cd72cd228598aebe58795000000000000000000000000000000000000000000a56fa5b99019a5c800000000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000011436f6d706f756e642044616920f09f938800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000046344414900000000000000000000000000000000000000000000000000000000",
        "CompoundLens": "0x",
        "DAI": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000003446169000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000034441490000000000000000000000000000000000000000000000000000000000",
        "StdComptroller": "0x",
        "Unitroller": "0x",
        "USDT": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000000d436f6d706f756e6420555344540000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000045553445400000000000000000000000000000000000000000000000000000000",
        "cUSDT": "0x000000000000000000000000d9ba894e0097f8cc2bbc9d24d308b98e36dc6d020000000000000000000000002eaa9d77ae4d8f9cdd9faacd44016e746485bddb0000000000000000000000005e237767da01d6fef0d238afe6a1ee02c43d82180000000000000000000000000000000000000000000000000000b5e620f48000000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000001800000000000000000000000000000000000000000000000000000000000000008000000000000000000000000e4cd9a61431fbd268ea842d68533561262c1751300000000000000000000000098394a121d26f90f4841e7bfe9dd4aba05e666e400000000000000000000000000000000000000000000000000000000000001c0000000000000000000000000000000000000000000000000000000000000000d436f6d706f756e642055534454000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005635553445400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000",
        "cBAT": "0x000000000000000000000000bf7a7169562078c96f0ec1a8afd6ae50f12e5a990000000000000000000000002eaa9d77ae4d8f9cdd9faacd44016e746485bddb0000000000000000000000006330d442a2d7ee4dc66c0adb9969e8702aefc9fe000000000000000000000000000000000000000000a56fa5b99019a5c800000000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000023436f6d706f756e6420426173696320417474656e74696f6e20546f6b656e20f09f9388000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000046342415400000000000000000000000000000000000000000000000000000000",
        "Base0bps_Slope2000bps": "0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002c68af0bb140000",
        "BAT": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000015426173696320417474656e74696f6e20546f6b656e000000000000000000000000000000000000000000000000000000000000000000000000000000000000034241540000000000000000000000000000000000000000000000000000000000",
        "cETH": "0x0000000000000000000000002eaa9d77ae4d8f9cdd9faacd44016e746485bddb0000000000000000000000001a43bfd39b15dcf444e17ab408c4b5be32deb7f5000000000000000000000000000000000000000000a56fa5b99019a5c800000000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000013436f6d706f756e6420457468657220f09f93880000000000000000000000000000000000000000000000000000000000000000000000000000000000000000046345544800000000000000000000000000000000000000000000000000000000",
        "cUsdtDelegate": "0x",
        "Base500bps_Slope1200bps": "0x00000000000000000000000000000000000000000000000000b1a2bc2ec5000000000000000000000000000000000000000000000000000001aa535d3d0c0000",
        "Timelock": "0x0000000000000000000000009c1856636d78c051dead6cab9c5699e4e25549e900000000000000000000000000000000000000000000000000000000000000b4",
        "Base200bps_Slope3000bps": "0x00000000000000000000000000000000000000000000000000470de4df8200000000000000000000000000000000000000000000000000000429d069189e0000",
        "cREP": "0x0000000000000000000000006e894660985207feb7cf89faf048998c71e8ee890000000000000000000000002eaa9d77ae4d8f9cdd9faacd44016e746485bddb0000000000000000000000006330d442a2d7ee4dc66c0adb9969e8702aefc9fe000000000000000000000000000000000000000000a56fa5b99019a5c800000000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000013436f6d706f756e6420417567757220f09f93880000000000000000000000000000000000000000000000000000000000000000000000000000000000000000046352455000000000000000000000000000000000000000000000000000000000",
        "ComptrollerG2": "0x",
        "WBTC": "0x",
        "REP": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000005417567757200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000035245500000000000000000000000000000000000000000000000000000000000",
        "cZRX": "0x000000000000000000000000ddea378a6ddc8afec82c36e9b0078826bf9e68b60000000000000000000000002eaa9d77ae4d8f9cdd9faacd44016e746485bddb0000000000000000000000006330d442a2d7ee4dc66c0adb9969e8702aefc9fe000000000000000000000000000000000000000000a56fa5b99019a5c800000000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000010436f6d706f756e6420307820f09f9388000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004635a525800000000000000000000000000000000000000000000000000000000",
        "cWBTC": "0x000000000000000000000000577d296678535e4903d59a4c929b718e1d575e0a0000000000000000000000002eaa9d77ae4d8f9cdd9faacd44016e746485bddb0000000000000000000000006330d442a2d7ee4dc66c0adb9969e8702aefc9fe00000000000000000000000000000000000000000000000000470de4df82000000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000019436f6d706f756e6420577261707065642042544320f09f93880000000000000000000000000000000000000000000000000000000000000000000000000000056357425443000000000000000000000000000000000000000000000000000000",
        "USDC": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000000855534420436f696e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000045553444300000000000000000000000000000000000000000000000000000000"
    },
    "Tokens": {
        "ZRX": {
            "name": "0x",
            "symbol": "ZRX",
            "decimals": 18,
            "address": "0xddea378A6dDC8AfeC82C36E9b0078826bf9e68B6"
        },
        "cUSDC": {
            "name": "Compound USD Coin 📈",
            "symbol": "cUSDC",
            "decimals": 8,
            "underlying": "0x4DBCdF9B62e891a7cec5A2568C3F4FAF9E8Abe2b",
            "contract": "CErc20",
            "initial_exchange_rate_mantissa": "200000000000000",
            "address": "0x5B281A6DdA0B271e91ae35DE655Ad301C976edb1"
        },
        "cDAI": {
            "name": "Compound Dai 📈",
            "symbol": "cDAI",
            "decimals": 8,
            "underlying": "0x5592EC0cfb4dbc12D3aB100b257153436a1f0FEa",
            "contract": "CErc20",
            "initial_exchange_rate_mantissa": "200000000000000000000000000",
            "address": "0x6D7F0754FFeb405d23C51CE938289d4835bE3b14"
        },
        "DAI": {
            "name": "Dai",
            "symbol": "DAI",
            "decimals": 18,
            "address": "0x5592EC0cfb4dbc12D3aB100b257153436a1f0FEa"
        },
        "USDT": {
            "description": "Standard",
            "name": "Compound USDT",
            "symbol": "USDT",
            "decimals": 18,
            "contract": "FaucetToken",
            "address": "0xD9BA894E0097f8cC2BBc9D24D308b98e36dc6D02"
        },
        "cUSDT": {
            "name": "Compound USDT",
            "symbol": "cUSDT",
            "decimals": 8,
            "underlying": "0xD9BA894E0097f8cC2BBc9D24D308b98e36dc6D02",
            "contract": "CErc20Delegator",
            "initial_exchange_rate_mantissa": "200000000000000",
            "admin": "0xe4cD9a61431FbD268ea842D68533561262C17513",
            "address": "0x2fB298BDbeF468638AD6653FF8376575ea41e768"
        },
        "cBAT": {
            "name": "Compound Basic Attention Token 📈",
            "symbol": "cBAT",
            "decimals": 8,
            "underlying": "0xbF7A7169562078c96f0eC1A8aFD6aE50f12e5A99",
            "contract": "CErc20",
            "initial_exchange_rate_mantissa": "200000000000000000000000000",
            "address": "0xEBf1A11532b93a529b5bC942B4bAA98647913002"
        },
        "BAT": {
            "name": "Basic Attention Token",
            "symbol": "BAT",
            "decimals": 18,
            "address": "0xbF7A7169562078c96f0eC1A8aFD6aE50f12e5A99"
        },
        "cETH": {
            "name": "Compound Ether 📈",
            "symbol": "cETH",
            "decimals": 8,
            "underlying": "",
            "contract": "CEther",
            "initial_exchange_rate_mantissa": "200000000000000000000000000",
            "address": "0xd6801a1DfFCd0a410336Ef88DeF4320D6DF1883e"
        },
        "cREP": {
            "name": "Compound Augur 📈",
            "symbol": "cREP",
            "decimals": 8,
            "underlying": "0x6e894660985207feb7cf89Faf048998c71E8EE89",
            "contract": "CErc20",
            "initial_exchange_rate_mantissa": "200000000000000000000000000",
            "address": "0xEBe09eB3411D18F4FF8D859e096C533CAC5c6B60"
        },
        "WBTC": {
            "description": "WBTC",
            "name": "Wrapped BTC",
            "symbol": "WBTC",
            "decimals": 8,
            "contract": "WBTCToken",
            "address": "0x577D296678535e4903D59A4C929B718e1D575e0A"
        },
        "REP": {
            "name": "Augur",
            "symbol": "REP",
            "decimals": 18,
            "address": "0x6e894660985207feb7cf89Faf048998c71E8EE89"
        },
        "cZRX": {
            "name": "Compound 0x 📈",
            "symbol": "cZRX",
            "decimals": 8,
            "underlying": "0xddea378A6dDC8AfeC82C36E9b0078826bf9e68B6",
            "contract": "CErc20",
            "initial_exchange_rate_mantissa": "200000000000000000000000000",
            "address": "0x52201ff1720134bBbBB2f6BC97Bf3715490EC19B"
        },
        "cWBTC": {
            "name": "Compound Wrapped BTC 📈",
            "symbol": "cWBTC",
            "decimals": 8,
            "underlying": "0x577D296678535e4903D59A4C929B718e1D575e0A",
            "contract": "CErc20",
            "initial_exchange_rate_mantissa": "20000000000000000",
            "address": "0x0014F450B8Ae7708593F4A46F8fa6E5D50620F96"
        },
        "USDC": {
            "description": "Standard",
            "name": "USD Coin",
            "symbol": "USDC",
            "decimals": 6,
            "address": "0x4DBCdF9B62e891a7cec5A2568C3F4FAF9E8Abe2b",
            "contract": "FaucetToken"
        }
    },
    "CTokenDelegate": {
        "cUsdtDelegate": {
            "address": "0x98394a121D26F90F4841e7BFE9dD4Aba05E666E4",
            "contract": "CErc20Delegate",
            "description": "Standard CErc20 Delegate"
        }
    },
    "cTokens": {
        "cZRX": {
            "name": "Compound 0x 📈",
            "symbol": "cZRX",
            "decimals": 8,
            "underlying": "0xddea378A6dDC8AfeC82C36E9b0078826bf9e68B6",
            "contract": "CErc20",
            "initial_exchange_rate_mantissa": "200000000000000000000000000",
            "address": "0x52201ff1720134bBbBB2f6BC97Bf3715490EC19B"
        },
        "cBAT": {
            "name": "Compound Basic Attention Token 📈",
            "symbol": "cBAT",
            "decimals": 8,
            "underlying": "0xbF7A7169562078c96f0eC1A8aFD6aE50f12e5A99",
            "contract": "CErc20",
            "initial_exchange_rate_mantissa": "200000000000000000000000000",
            "address": "0xEBf1A11532b93a529b5bC942B4bAA98647913002"
        },
        "cDAI": {
            "name": "Compound Dai 📈",
            "symbol": "cDAI",
            "decimals": 8,
            "underlying": "0x5592EC0cfb4dbc12D3aB100b257153436a1f0FEa",
            "contract": "CErc20",
            "initial_exchange_rate_mantissa": "200000000000000000000000000",
            "address": "0x6D7F0754FFeb405d23C51CE938289d4835bE3b14"
        },
        "cREP": {
            "name": "Compound Augur 📈",
            "symbol": "cREP",
            "decimals": 8,
            "underlying": "0x6e894660985207feb7cf89Faf048998c71E8EE89",
            "contract": "CErc20",
            "initial_exchange_rate_mantissa": "200000000000000000000000000",
            "address": "0xEBe09eB3411D18F4FF8D859e096C533CAC5c6B60"
        },
        "cETH": {
            "name": "Compound Ether 📈",
            "symbol": "cETH",
            "decimals": 8,
            "underlying": "",
            "contract": "CEther",
            "initial_exchange_rate_mantissa": "200000000000000000000000000",
            "address": "0xd6801a1DfFCd0a410336Ef88DeF4320D6DF1883e"
        },
        "cUSDC": {
            "name": "Compound USD Coin 📈",
            "symbol": "cUSDC",
            "decimals": 8,
            "underlying": "0x4DBCdF9B62e891a7cec5A2568C3F4FAF9E8Abe2b",
            "contract": "CErc20",
            "initial_exchange_rate_mantissa": "200000000000000",
            "address": "0x5B281A6DdA0B271e91ae35DE655Ad301C976edb1"
        },
        "cWBTC": {
            "name": "Compound Wrapped BTC 📈",
            "symbol": "cWBTC",
            "decimals": 8,
            "underlying": "0x577D296678535e4903D59A4C929B718e1D575e0A",
            "contract": "CErc20",
            "initial_exchange_rate_mantissa": "20000000000000000",
            "address": "0x0014F450B8Ae7708593F4A46F8fa6E5D50620F96"
        },
        "cUSDT": {
            "name": "Compound USDT",
            "symbol": "cUSDT",
            "decimals": 8,
            "underlying": "0xD9BA894E0097f8cC2BBc9D24D308b98e36dc6D02",
            "contract": "CErc20Delegator",
            "initial_exchange_rate_mantissa": "200000000000000",
            "admin": "0xe4cD9a61431FbD268ea842D68533561262C17513",
            "address": "0x2fB298BDbeF468638AD6653FF8376575ea41e768"
        }
    },
    "InterestRateModel": {
        "Base500bps_Slope1200bps": {
            "name": "Base500bps_Slope1200bps",
            "contract": "WhitePaperInterestRateModel",
            "description": "WhitePaper baseRate=50000000000000000 multiplier=120000000000000000",
            "base": "50000000000000000",
            "slope": "120000000000000000",
            "address": "0xE12630c8Fdd7d0096c9Cd72Cd228598AEBe58795"
        },
        "Base0bps_Slope2000bps": {
            "name": "Base0bps_Slope2000bps",
            "contract": "WhitePaperInterestRateModel",
            "description": "WhitePaper baseRate=0 multiplier=200000000000000000",
            "base": "0",
            "slope": "200000000000000000",
            "address": "0x1A43BFd39B15DcF444e17Ab408C4b5be32DEB7F5"
        },
        "Base200bps_Slope3000bps": {
            "name": "Base200bps_Slope3000bps",
            "contract": "WhitePaperInterestRateModel",
            "description": "WhitePaper baseRate=20000000000000000 multiplier=300000000000000000",
            "base": "20000000000000000",
            "slope": "300000000000000000",
            "address": "0x6330D442A2D7eE4DC66C0adb9969e8702aEfc9fE"
        },
        "Base200bps_Slope2000bps_Jump20000bps_Kink90": {
            "name": "Base200bps_Slope2000bps_Jump20000bps_Kink90",
            "contract": "JumpRateModel",
            "description": "JumpRateModel baseRate=20000000000000000 multiplier=200000000000000000 jump=2000000000000000000 kink=900000000000000000",
            "base": "20000000000000000",
            "slope": "200000000000000000",
            "jump": "2000000000000000000",
            "kink": "900000000000000000",
            "address": "0x5e237767da01d6fEF0D238aFe6a1EE02c43D8218"
        }
    }

**Review by DioXi95 — APPROVED** [review]

**Review by weioocom — APPROVED** [review]

**Review by Asim-tech235 — APPROVED** [review]
[****]() Resolves #10, resolves #123, resolves octo-org/octo-

**Review by kopetsss — APPROVED** [review]

**Review by Thugnasty777 — APPROVED** [review]

**Review by kopetsss — APPROVED** [review]

**Review by kopetsss — APPROVED** [review]

**Review by kopetsss — APPROVED** [review]

**Review by Thugnasty777 — APPROVED** [review]

**Comment by Thugnasty777** [comment]
Merge

**Review by Thugnasty777 — APPROVED** [review]

**Comment by Tuananh11021986** [comment]
Ok .thanks

Vào 08:47 AM, CN, 30 Th5, 2021 kopetsss ***@***.***> đã viết:

**Comment by Tuananh11021986** [comment]
What do I need to do next?

Vào 09:14 AM, CN, 30 Th5, 2021 kopetsss ***@***.***> đã viết:

**Pull request merged**
